contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #postcuration channel"
    url: https://nfcore.slack.com/channels/postcuration
    about: Discussion about the nf-core/postcuration pipeline
